apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-config
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;

        location / {
          root /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }

        access_log  /var/log/nginx/housing-subsidies-frontend-access.log combined;
        error_log   /var/log/nginx/housing-subsidies-frontend-error.log debug;
    }
